services:
  jenkins:
    build: .
    privileged: true    # Needed if you want Jenkins to run Docker inside Docker
    user: root
    ports:
      - "3000:8080"
      - "8000:8000"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Optional: allows Jenkins to run Docker commands

volumes:
  jenkins_home: