INSERT INTO person(id,first_name,last_name,email,gender) VALUES
(1, 'Finn', 'Schutt', 'fschutt0@dailymail.co.uk', 'Male'),
(2, 'Martynne', 'Cauldfield', 'mcauldfield1@ebay.co.uk', 'Female'),
(3, 'Torre', 'Caldecutt', 'tcaldecutt2@clickbank.net', 'Bigender'),
(4, 'Filmore', 'Perryman', 'fperryman3@qq.com', 'Male'),
(5, 'Fran', 'Guerrieri', 'fguerrieri4@plala.or.jp', 'Female'),
(6, 'Lesya', 'Drejer', 'ldrejer5@va.gov', 'Female'),
(7, 'Gideon', 'Richley', 'grichley6@mapy.cz', 'Male'),
(8, 'Gloriane', 'Pharo', 'gpharo7@opensource.org', 'Female'),
(9, 'Amitie', 'Lazenby', 'alazenby8@google.it', 'Female'),
(10, 'Sean', 'Whitehorne', 'swhitehorne9@blogspot.com', 'Non-binary'),
(11, 'Shauna', 'Fritschmann', 'sfritschmanna@geocities.jp', 'Female'),
(12, 'Cooper', 'Cato', 'ccatob@example.com', 'Male'),
(13, 'Melli', 'Wickham', 'mwickhamc@npr.org', 'Genderqueer'),
(14, 'Prinz', 'Bondley', 'pbondleyd@cbsnews.com', 'Male'),
(15, 'Suzanne', 'Shilito', 'sshilitoe@state.tx.us', 'Female'),
(16, 'Alvan', 'Kneafsey', 'akneafseyf@paypal.com', 'Male'),
(17, 'Dayle', 'Cobden', 'dcobdeng@desdev.cn', 'Female'),
(18, 'Haroun', 'Riddles', 'hriddlesh@samsung.com', 'Male'),
(19, 'Abner', 'Mabbett', 'amabbetti@istockphoto.com', 'Male'),
(20, 'Augustin', 'Santarelli', 'asantarellij@360.cn', 'Male'),
(21, 'Michaela', 'Hordle', 'mhordlek@constantcontact.com', 'Female'),
(22, 'Gwenore', 'Wannes', 'gwannesl@hostgator.com', 'Female'),
(23, 'Tiffanie', 'Pitherick', 'tpitherickm@hatena.ne.jp', 'Non-binary'),
(24, 'Becca', 'Mortimer', 'bmortimern@slate.com', 'Female'),
(25, 'Oralle', 'Smallpiece', 'osmallpieceo@zdnet.com', 'Female'),
(26, 'Max', 'Houliston', 'mhoulistonp@amazonaws.com', 'Female'),
(27, 'Brandy', 'Boast', 'bboastq@ovh.net', 'Male'),
(28, 'Terrie', 'Layson', 'tlaysonr@netlog.com', 'Female'),
(29, 'Hobie', 'Tomalin', 'htomalins@businesswire.com', 'Male'),
(30, 'Culver', 'Muldownie', 'cmuldowniet@mozilla.com', 'Male');

INSERT INTO serie (title, genre, nb_episode, note)
VALUES
('Breaking Bad', 'Crime, Drama, Thriller', 62, 10),
('Game of Thrones', 'Action, Adventure, Drama', 73, 9),
('Stranger Things', 'Drama, Fantasy, Horror', 34, 8),
('The Office (US)', 'Comedy', 201, 9),
('Friends', 'Comedy, Romance', 236, 9),
('The Crown', 'Biography, Drama, History', 60, 8),
('The Mandalorian', 'Action, Adventure, Fantasy', 24, 8),
('Dark', 'Crime, Drama, Mystery', 26, 9),
('Peaky Blinders', 'Crime, Drama', 36, 9),
('The Witcher', 'Action, Adventure, Drama', 24, 7),
('The Boys', 'Action, Crime, Drama', 24, 8),
('Sherlock', 'Crime, Drama, Mystery', 13, 9),
('House of the Dragon', 'Action, Adventure, Drama', 10, 8),
('Black Mirror', 'Drama, Sci-Fi, Thriller', 27, 8),
('How I Met Your Mother', 'Comedy, Romance', 208, 8),
('Narcos', 'Biography, Crime, Drama', 30, 8),
('Lupin', 'Action, Crime, Drama', 17, 8),
('Better Call Saul', 'Crime, Drama', 63, 9),
('Vikings', 'Action, Adventure, Drama', 89, 8),
('The Last of Us', 'Action, Adventure, Drama', 9, 9);